#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

write_files:
  - path: /etc/gitlab-runner/config.toml
    permissions: '0644'
    content: |
      concurrent = 1
      check_interval = 0
      shutdown_timeout = 0

      [session_server]
        session_timeout = 1800

      [[runners]]
        name = "gitlab-runner-manager"
        url = "https://gitlab.com/"
        token = "<your-token-here>"
        token_expires_at = 0001-01-01T00:00:00Z
        executor = "instance"
        [runners.cache]
          MaxUploadedArchiveSize = 0
          [runners.cache.s3]
          [runners.cache.gcs]
          [runners.cache.azure]
      # Autoscaler config
        [runners.autoscaler]
          plugin = "azure" # for >= 16.11, ensure you run `gitlab-runner fleeting install` to automatically install the plugin

          capacity_per_instance = 1
          max_use_count = 1
          max_instances = 10

          [runners.autoscaler.plugin_config] # plugin specific configuration (see plugin documentation)
            name                = "<name>"
            subscription_id     = "<subscription-id>"
            resource_group_name = "<resource-group-name>"

          [runners.autoscaler.connector_config]
            username               = "adminuser"
            password               = "<password>"
            use_static_credentials = true
            timeout                = "10m"
            use_external_addr      = true

          [[runners.autoscaler.policy]]
            idle_count = 1
            idle_time  = "20m0s"

runcmd:
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce
  - systemctl enable docker
  
  # Install GitLab Runner
  - curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
  - apt-get install -y gitlab-runner

  - chown -R gitlab-runner:gitlab-runner /etc/gitlab-runner

  # Install the autoscaler plugin
  - gitlab-runner fleeting install

  # Register the runner
  - gitlab-runner register --non-interactive --executor "instance" --url "https://gitlab.com/"  --token "<token>"

  - systemctl restart gitlab-runner
